const sections = [
    { id: "nature", title: "1. Nature of the Service", content: "Juriq provides an AI-powered copilot designed to assist founders, students, and lawyers in reviewing and understanding legal documents. The features provided by Juriq, including but not limited to clause summaries, risk identification, and suggested edits, are generated by artificial intelligence models and are strictly for informational and educational purposes." },
    { id: "no-advice", title: "2. Not Legal Advice", content: "Juriq is not a law firm. We do not provide legal advice, legal opinions, or legal representation. The use of our service, including any information or outputs generated by the AI, does not constitute legal advice and cannot replace the counsel of a qualified attorney licensed in your jurisdiction." },
    { id: "no-relationship", title: "3. No Attorney-Client Relationship", content: "Using Juriq, uploading documents, or interacting with the AI copilot does not create an attorney-client relationship between you and Juriq, its employees, or its affiliates. Your communications with Juriq are not protected by attorney-client privilege." },
    { id: "accuracy", title: "4. Accuracy and Completeness", content: "While we strive to provide helpful and accurate informational assistance, AI models can be unpredictable. Outputs may be incomplete, outdated, or entirely inaccurate (sometimes called \"hallucinations\"). You should never rely solely on Juriq for critical legal or business decisions without independent verification." },
    { id: "independent-counsel", title: "5. Independent Legal Counsel", content: "For any high-stakes transactions, litigation, dispute resolution, or jurisdiction-specific matters, we strongly recommend consulting with qualified legal counsel. Juriq is intended to be a first-pass tool to accelerate your understanding, not a final legal authority." }
];

export default function Disclaimer() {
    return (
        <div className="px-4 py-20 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl">
                <h1 className="font-display text-4xl font-bold text-foreground">AI Disclaimer & No Legal Advice</h1>
                <p className="mt-3 text-sm text-muted-foreground">Last updated: March 10, 2026</p>

                {/* TOC */}
                <nav className="mt-8 rounded-xl border border-border/50 bg-card p-5">
                    <h3 className="mb-3 font-display text-sm font-semibold text-foreground">Contents</h3>
                    <ul className="space-y-1.5">
                        {sections.map((s) => (
                            <li key={s.id}>
                                <a href={`#${s.id}`} className="text-sm text-link hover:text-foreground transition-default">{s.title}</a>
                            </li>
                        ))}
                    </ul>
                </nav>

                <div className="mt-10 space-y-10">
                    {sections.map((s) => (
                        <section key={s.id} id={s.id}>
                            <h2 className="font-display text-lg font-bold text-foreground">{s.title}</h2>
                            <p className="mt-3 leading-relaxed text-muted-foreground text-sm">{s.content}</p>
                        </section>
                    ))}
                </div>
            </div>
        </div>
    );
}
